export const START_LISTEN_DEVICE_EVENTS = 'START_LISTEN_DEVICE_EVENTS';
export const STOP_LISTEN_DEVICE_EVENTS = 'STOP_LISTEN_DEVICE_EVENTS';

export const DEVICE_CONNECTED = 'DEVICE_CONNECTED';
export const DEVICE_DISCONNECTED = 'DEVICE_DISCONNECTED';

export const GET_APP_STATS_SUCCESS = 'GET_APP_STATS_SUCCESS';
export const GET_APP_STATS_FAILURE = 'GET_APP_STATS_FAILURE';

export const GET_PUBLIC_KEY_REQUEST = 'GET_PUBLIC_KEY_REQUEST';
export const GET_PUBLIC_KEY_FAILURE = 'GET_PUBLIC_KEY_FAILURE';
export const GET_PUBLIC_KEY_SUCCESS = 'GET_PUBLIC_KEY_SUCCESS';

export const PUBLIC_KEY_DISPLAY_REQUEST = 'PUBLIC_KEY_DISPLAY_REQUEST';
export const PUBLIC_KEY_DISPLAY_SUCCESS = 'PUBLIC_KEY_DISPLAY_SUCCESS';
export const PUBLIC_KEY_DISPLAY_FAILURE = 'PUBLIC_KEY_DISPLAY_FAILURE';

export const GET_APP_INFO_REQUEST = 'GET_APP_INFO_REQUEST';
export const GET_APP_INFO_FAILURE = 'GET_APP_INFO_FAILURE';
export const GET_APP_INFO_SUCCESS = 'GET_APP_INFO_SUCCESS';

export const CREATE_CONNECTION_REQUEST = 'CREATE_CONNECTION_REQUEST';
export const CREATE_CONNECTION_SUCCESS = 'CREATE_CONNECTION_SUCCESS';
export const CREATE_CONNECTION_FAILURE = 'CREATE_CONNECTION_FAILURE';

export const GET_ACCOUNTS_REQUEST = 'GET_ACCOUNTS_REQUEST';
export const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS';
export const GET_ACCOUNTS_FAILURE = 'GET_ACCOUNTS_FAILURE';

export const GET_ACCOUNT_REQUEST = 'GET_ACCOUNT_REQUEST';
export const GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS';
export const GET_ACCOUNT_FAILURE = 'GET_ACCOUNT_FAILURE';

export const GET_PRODUCERS_REQUEST = 'GET_PRODUCERS_REQUEST';
export const GET_PRODUCERS_SUCCESS = 'GET_PRODUCERS_SUCCESS';
export const GET_PRODUCERS_FAILURE = 'GET_PRODUCERS_FAILURE';

export const GET_ACTIONS_REQUEST = 'GET_ACTIONS_REQUEST';
export const GET_ACTIONS_SUCCESS = 'GET_ACTIONS_SUCCESS';
export const GET_ACTIONS_FAILURE = 'GET_ACTIONS_FAILURE';

export const GET_CURRENCY_BALANCE_REQUEST = 'GET_CURRENCY_BALANCE_REQUEST';
export const GET_CURRENCY_BALANCE_SUCCESS = 'GET_CURRENCY_BALANCE_SUCCESS';
export const GET_CURRENCY_BALANCE_FAILURE = 'GET_CURRENCY_BALANCE_FAILURE';

export const CREATE_TRANSFER_TX_REQUEST = 'CREATE_TRANSFER_TX_REQUEST';
export const CREATE_TRANSFER_TX_SUCCESS = 'CREATE_TRANSFER_TX_SUCCESS';
export const CREATE_TRANSFER_TX_FAILURE = 'CREATE_TRANSFER_TX_FAILURE';

export const SIGN_TRANSACTION_REQUEST = 'SIGN_TRANSACTION_REQUEST';
export const SIGN_TRANSACTION_SUCCESS = 'SIGN_TRANSACTION_SUCCESS';
export const SIGN_TRANSACTION_FAILURE = 'SIGN_TRANSACTION_FAILURE';

export const APP_LEDGER_CONNECTION_STATUS = 'APP_LEDGER_CONNECTION_STATUS';
export const APP_NODE_CONNECTION_STATUS = 'APP_NODE_CONNECTION_STATUS';
export const APP_ACCOUNT_FOUND = 'APP_ACCOUNT_FOUND';

export const ADD_TOKEN = 'ADD_TOKEN';
