export const DEVICE_CONNECTED = 'DEVICE_CONNECTED';
export const DEVICE_DISCONNECTED = 'DEVICE_DISCONNECTED';

export const GET_PUBLIC_KEY_REQUEST = 'GET_PUBLIC_KEY_REQUEST';
export const GET_PUBLIC_KEY_FAILURE = 'GET_PUBLIC_KEY_FAILURE';
export const GET_PUBLIC_KEY_SUCCESS = 'GET_PUBLIC_KEY_SUCCESS';