export const START_LISTEN_DEVICE_EVENTS = 'START_LISTEN_DEVICE_EVENTS';
export const STOP_LISTEN_DEVICE_EVENTS = 'STOP_LISTEN_DEVICE_EVENTS';

export const DEVICE_CONNECTED = 'DEVICE_CONNECTED';
export const DEVICE_DISCONNECTED = 'DEVICE_DISCONNECTED';

export const GET_APP_STATS_REQUEST = 'GET_APP_STATS_REQUEST';
export const GET_APP_STATS_SUCCESS = 'GET_APP_STATS_SUCCESS';
export const GET_APP_STATS_FAILURE = 'GET_APP_STATS_FAILURE';

export const GET_PUBLIC_KEY_REQUEST = 'GET_PUBLIC_KEY_REQUEST';
export const GET_PUBLIC_KEY_FAILURE = 'GET_PUBLIC_KEY_FAILURE';
export const GET_PUBLIC_KEY_SUCCESS = 'GET_PUBLIC_KEY_SUCCESS';

export const PUBLIC_KEY_DISPLAY_REQUEST = 'PUBLIC_KEY_DISPLAY_REQUEST';
export const PUBLIC_KEY_DISPLAY_SUCCESS = 'PUBLIC_KEY_DISPLAY_SUCCESS';
export const PUBLIC_KEY_DISPLAY_FAILURE = 'PUBLIC_KEY_DISPLAY_FAILURE';

export const GET_APP_INFO_REQUEST = 'GET_APP_INFO_REQUEST';
export const GET_APP_INFO_FAILURE = 'GET_APP_INFO_FAILURE';
export const GET_APP_INFO_SUCCESS = 'GET_APP_INFO_SUCCESS';

export const CLEAR_CONNECTION = 'CLEAR_CONNECTION';
export const CREATE_CONNECTION_REQUEST = 'CREATE_CONNECTION_REQUEST';
export const CREATE_CONNECTION_SUCCESS = 'CREATE_CONNECTION_SUCCESS';
export const CREATE_CONNECTION_FAILURE = 'CREATE_CONNECTION_FAILURE';

export const GET_ACCOUNTS_REQUEST = 'GET_ACCOUNTS_REQUEST';
export const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS';
export const GET_ACCOUNTS_FAILURE = 'GET_ACCOUNTS_FAILURE';

export const GET_GLOBAL_REQUEST = 'GET_GLOBAL_REQUEST';
export const GET_GLOBAL_SUCCESS = 'GET_GLOBAL_SUCCESS';
export const GET_GLOBAL_FAILURE = 'GET_GLOBAL_FAILURE';

export const SET_ACTIVE_ACCOUNT = 'SET_ACTIVE_ACCOUNT';

export const GET_ACCOUNT_REQUEST = 'GET_ACCOUNT_REQUEST';
export const GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS';
export const GET_ACCOUNT_FAILURE = 'GET_ACCOUNT_FAILURE';

export const GET_CURRENCYSTATS_REQUEST = 'GET_CURRENCYSTATS_REQUEST';
export const GET_CURRENCYSTATS_SUCCESS = 'GET_CURRENCYSTATS_SUCCESS';
export const GET_CURRENCYSTATS_FAILURE = 'GET_CURRENCYSTATS_FAILURE';

export const GET_CURRENCY_EXCHANGE_PRICE_REQUEST =
  'GET_CURRENCY_EXCHANGE_PRICE_REQUEST';
export const GET_CURRENCY_EXCHANGE_PRICE_SUCCESS =
  'GET_CURRENCY_EXCHANGE_PRICE_SUCCESS';
export const GET_CURRENCY_EXCHANGE_PRICE_FAILURE =
  'GET_CURRENCY_EXCHANGE_PRICE_FAILURE';

export const GET_PRODUCERS_REQUEST = 'GET_PRODUCERS_REQUEST';
export const GET_PRODUCERS_SUCCESS = 'GET_PRODUCERS_SUCCESS';
export const GET_PRODUCERS_FAILURE = 'GET_PRODUCERS_FAILURE';

export const GET_ACTIONS_REQUEST = 'GET_ACTIONS_REQUEST';
export const GET_ACTIONS_SUCCESS = 'GET_ACTIONS_SUCCESS';
export const GET_ACTIONS_FAILURE = 'GET_ACTIONS_FAILURE';

export const GET_CURRENCY_BALANCE_REQUEST = 'GET_CURRENCY_BALANCE_REQUEST';
export const GET_CURRENCY_BALANCE_SUCCESS = 'GET_CURRENCY_BALANCE_SUCCESS';
export const GET_CURRENCY_BALANCE_FAILURE = 'GET_CURRENCY_BALANCE_FAILURE';

export const RESET_TRANSACTIONS_STATE = 'RESET_TRANSACTIONS_STATE';
export const TRANSFER_TOKEN_REQUEST = 'TRANSFER_TOKEN_REQUEST';
export const TRANSFER_TOKEN_SUCCESS = 'TRANSFER_TOKEN_SUCCESS';
export const TRANSFER_TOKEN_FAILURE = 'TRANSFER_TOKEN_FAILURE';
export const TRANSFER_TOKEN_CONSTRUCTED = 'TRANSFER_TOKEN_CONSTRUCTED';
export const TRANSFER_TOKEN_SIGNED = 'TRANSFER_TOKEN_SIGNED';

export const DELEGATE_UNDELEGATE_REQUEST = 'DELEGATE_UNDELEGATE_REQUEST';
export const DELEGATE_UNDELEGATE_SUCCESS = 'DELEGATE_UNDELEGATE_SUCCESS';
export const DELEGATE_UNDELEGATE_FAILURE = 'DELEGATE_UNDELEGATE_FAILURE';

export const DELEGATE_REQUEST = 'DELEGATE_REQUEST';
export const DELEGATE_SUCCESS = 'DELEGATE_SUCCESS';
export const DELEGATE_FAILURE = 'DELEGATE_FAILURE';
export const DELEGATE_CONSTRUCTED = 'DELEGATE_CONSTRUCTED';
export const DELEGATE_SIGNED = 'DELEGATE_SIGNED';

export const UNDELEGATE_REQUEST = 'UNDELEGATE_REQUEST';
export const UNDELEGATE_SUCCESS = 'UNDELEGATE_SUCCESS';
export const UNDELEGATE_FAILURE = 'UNDELEGATE_FAILURE';
export const UNDELEGATE_CONSTRUCTED = 'UNDELEGATE_CONSTRUCTED';
export const UNDELEGATE_SIGNED = 'UNDELEGATE_SIGNED';

export const VOTEPRODUCER_REQUEST = 'VOTEPRODUCER_REQUEST';
export const VOTEPRODUCER_SUCCESS = 'VOTEPRODUCER_SUCCESS';
export const VOTEPRODUCER_FAILURE = 'VOTEPRODUCER_FAILURE';
export const VOTEPRODUCER_CONSTRUCTED = 'VOTEPRODUCER_CONSTRUCTED';
export const VOTEPRODUCER_SIGNED = 'VOTEPRODUCER_SIGNED';

export const BUYRAM_REQUEST = 'BUYRAM_REQUEST';
export const BUYRAM_SUCCESS = 'BUYRAM_SUCCESS';
export const BUYRAM_FAILURE = 'BUYRAM_FAILURE';
export const BUYRAM_CONSTRUCTED = 'BUYRAM_CONSTRUCTED';
export const BUYRAM_SIGNED = 'BUYRAM_SIGNED';

export const APP_LEDGER_CONNECTION_STATUS = 'APP_LEDGER_CONNECTION_STATUS';
export const APP_NODE_CONNECTION_STATUS = 'APP_NODE_CONNECTION_STATUS';
export const APP_ACCOUNT_FOUND = 'APP_ACCOUNT_FOUND';

export const ADD_TOKEN = 'ADD_TOKEN';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';

export const RESET_FAILURE = 'RESET_FAILURE';
